PROJECT_NAME_MAX_LENGTH = 200

PROJECT_STATUS_OPEN = "open"
PROJECT_STATUS_CLOSED = "closed"
PROJECT_STATUS_CHOICES = [
    (PROJECT_STATUS_OPEN, "Открыт"),
    (PROJECT_STATUS_CLOSED, "Закрыт"),
]
PROJECT_STATUS_MAX_LENGTH = max(len(status) for status, _ in PROJECT_STATUS_CHOICES)
