# Generated by Django 5.2.4 on 2026-05-05 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ('name',), 'verbose_name': 'навык', 'verbose_name_plural': 'навыки'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('surname', 'name', 'email'), 'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
    ]
